[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.4", features = ["derive"] }
counter = "0.7.0"
dirs = "6.0.0"
dotenv = "0.15.0"
reqwest = { version = "0.12.24", features = ["blocking"] }

[[bin]]
name = "scaffold"
path = "src/bin/scaffold.rs"
